### ISSUE TITLE
 MongoDB Adapter throws Request error! MongoError : pool destroyed

### ISSUE THREAD

**Issue by wiedmannj** [energychain/STROMDAO_EAFs#7]
If run in stateful mode with a MongoDB configured as a backend database on a single node, the log shows `Request error! MongoError : pool destroyed`. As soon as this appears the service needs to be restarted to function properly.

**Comment by zoernert** [comment]
Root cause identified: https://github.com/moleculerjs/moleculer-db/issues/333

**Comment by zoernert** [comment]
Partly fixable with a local installation of  MongoDB. However the handling of the pool seems to be broken in the original moleculer-db adapter.
